# Generated by Django 3.0.9 on 2020-10-15 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Direct Phone')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Main Phone')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Fax')),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(default=main.models.next_pnum, max_length=12, primary_key=True, serialize=False, verbose_name='Project Number')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('P', 'Proposal'), ('L', 'Lost'), ('D', 'Development'), ('M', 'Maintenance'), ('C', 'Closed')], max_length=1, verbose_name='Status')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Client')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='quantity')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('notes', models.CharField(blank=True, default='', max_length=280, verbose_name='Notes')),
                ('billed', models.BooleanField(default=False, verbose_name='Billed?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
            options={
                'db_table': 'hours',
                'ordering': ['-date', 'project__number'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
    ]
